---
name: Bug Report
description: Report a bug encountered while using Frappe Health
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Welcome to Frappe Health issue tracker! Before creating an issue, please consider the following:

        1. This tracker should only be used to report bugs and request features / enhancements to Frappe Health
            - For questions and general support, checkout the [documentation](https://frappehealth.com/docs) or use the [forum](https://discuss.frappe.io/c/healthcare/58) to get inputs from the open source community.
            - For documentation issues, propose edit on the [documentation site](https://frappehealth.com/docs) directly.
        2. When making a bug report, make sure you provide all required information. The easier it is for
           maintainers to reproduce, the faster it'll be fixed.
        3. If you think you know what the reason for the bug is, share it with us. Maybe put in a PR 😉

  - type: textarea
    id: bug-info
    attributes:
      label: Information about bug
      description: Also tell us, what did you expect to happen? If applicable, add screenshots to help explain your problem.
      placeholder: Please provide as much information as possible.
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Select the affected module of Frappe Health.
      multiple: true
      options:
        - Outpatient Module
        - Inpatient ADT
        - Laboratory
        - Clinical Procedure
        - Rehab & Physiotherapy
        - Patient History
        - Setup / Configuration
        - Integration with ERPNext modules
        - Regional / Other Integrations
    validations:
      required: true

  - type: textarea
    id: exact-version
    attributes:
      label: Version
      description: Share exact version number of Frappe, ERPNext and Frappe Health you are using.
      placeholder: |
        Frappe version -
        ERPNext version -
        Frappe Health version -
    validations:
      required: true

  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      options:
        - docker
        - easy-install
        - manual install
        - FrappeCloud
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output / Stack trace / Full Error Message.
      description: Please copy and paste any relevant log output. This will be automatically formatted.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/frappe/health/blob/develop/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
...
